#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=GbzQSZG47sY permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
echo "custom_404" > /var/www/html/custom_404.html
service nginx start
